name: release-check

on:
  push:
    branches: ["main"]
    paths:
      - ".goreleaser.yaml"
      - ".github/workflows/release.yml"
  pull_request:
    paths:
      - ".goreleaser.yaml"
      - ".github/workflows/release.yml"

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Goreleaser check
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check
